apiVersion: apps/v1
kind: Deployment
metadata:
  name: countries-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countries
  template:
    metadata:
      labels:
        app: countries
    spec:
      containers:
        - name: countries
          image: razaviv/countries
          env:
            - name: MONGO_URI
              value: 'mongodb://countries-mongo-srv:27017/countries'
---
apiVersion: v1
kind: Service
metadata:
  name: countries-srv
spec:
  selector:
    app: countries
  ports:
    - name: countries
      protocol: TCP
      port: 3003
      targetPort: 3003
